import { Vehicle } from '@/core/Vehicle/domain/Vehicle'
import { VehicleDTO } from '@/core/Vehicle/infrastructure/dto/Vehicle.dto'

const emptyDTO: VehicleDTO = {
  id: '',
  year: '2024',
  make: 'Toyota',
  model: '',
  atvType: '',
  fuelType: 'Regular',
  VClass: 'Midsize Cars',
  drive: 'Front-Wheel Drive',
  trany: 'Automatic (S8)',
  cylinders: '',
  displ: '',
  evMotor: '',
  city08: '0',
  highway08: '0',
  comb08: '0',
  cityE: '0.0',
  highwayE: '0.0',
  combE: '0.0',
  co2TailpipeGpm: '0.0',
  fuelCost08: '0',
  range: '0',
  rangeA: '',
  combinedUF: '0.0',
  feScore: '-1',
  ghgScore: '-1',
  youSaveSpend: '0',
}

/** 2024 Toyota Camry, gasoline (API id 47085) */
export const camryDTO: VehicleDTO = {
  ...emptyDTO,
  id: '47085',
  model: 'Camry',
  cylinders: '6',
  displ: '3.5',
  city08: '22',
  highway08: '33',
  comb08: '26',
  co2TailpipeGpm: '338.0',
  fuelCost08: '2500',
  feScore: '5',
  ghgScore: '5',
  youSaveSpend: '-1750',
}

/** 2024 Toyota Prius Prime SE, plug-in hybrid (API id 47501) */
export const priusPrimeDTO: VehicleDTO = {
  ...emptyDTO,
  id: '47501',
  model: 'Prius Prime SE',
  atvType: 'Plug-in Hybrid',
  fuelType: 'Regular Gas and Electricity',
  trany: 'Automatic (variable gear ratios)',
  cylinders: '4',
  displ: '2.0',
  evMotor: '120 kW AC Induction',
  city08: '53',
  highway08: '51',
  comb08: '52',
  cityE: '24.0',
  highwayE: '29.0',
  combE: '26.0',
  co2TailpipeGpm: '50.0',
  fuelCost08: '1250',
  range: '600',
  rangeA: '45',
  combinedUF: '0.71',
  feScore: '9',
  ghgScore: '10',
  youSaveSpend: '7500',
}

/** 2024 Toyota bZ4X Limited, electric (API id 47219) */
export const bz4xDTO: VehicleDTO = {
  ...emptyDTO,
  id: '47219',
  model: 'bZ4X Limited',
  atvType: 'EV',
  fuelType: 'Electricity',
  VClass: 'Small Sport Utility Vehicle 2WD',
  trany: 'Automatic (A1)',
  evMotor: '160 kW AC PMSM',
  city08: '121',
  highway08: '102',
  comb08: '112',
  cityE: '27.8528',
  highwayE: '33.0441',
  combE: '30.1384',
  fuelCost08: '700',
  range: '236',
  feScore: '10',
  ghgScore: '10',
  youSaveSpend: '6000',
}

/** The same vehicles once built, as the rest of the app sees them */
export const camry: Vehicle = {
  id: '47085',
  year: 2024,
  make: 'Toyota',
  model: 'Camry',
  trim: 'Auto (S8), 6 cyl, 3.5 L',
  fuel: 'gasoline',
  fuelType: 'Regular',
  vehicleClass: 'Midsize Cars',
  drive: 'Front-Wheel Drive',
  transmission: 'Automatic (S8)',
  cylinders: 6,
  displacement: 3.5,
  electricMotor: '',
  liters: { city: 10.7, highway: 7.1, combined: 9 },
  electricity: null,
  co2: 210,
  annualFuelCostUsd: 2500,
  range: null,
  electricRange: null,
  utilityFactor: 0,
  fuelEconomyScore: 5,
  greenhouseGasScore: 5,
  fiveYearSavingsUsd: -1750,
}

export const bz4x: Vehicle = {
  ...camry,
  id: '47219',
  model: 'bZ4X Limited',
  trim: 'Auto (A1)',
  fuel: 'electric',
  fuelType: 'Electricity',
  vehicleClass: 'Small Sport Utility Vehicle 2WD',
  transmission: 'Automatic (A1)',
  cylinders: null,
  displacement: null,
  electricMotor: '160 kW AC PMSM',
  liters: null,
  electricity: { city: 17.3, highway: 20.5, combined: 18.7 },
  co2: 0,
  annualFuelCostUsd: 700,
  range: 380,
  fuelEconomyScore: 10,
  greenhouseGasScore: 10,
  fiveYearSavingsUsd: 6000,
}

export const priusPrime: Vehicle = {
  ...camry,
  id: '47501',
  model: 'Prius Prime SE',
  trim: undefined,
  fuel: 'plugInHybrid',
  fuelType: 'Regular Gas and Electricity',
  transmission: 'Automatic (variable gear ratios)',
  cylinders: 4,
  displacement: 2,
  electricMotor: '120 kW AC Induction',
  liters: { city: 4.4, highway: 4.6, combined: 4.5 },
  electricity: { city: 14.9, highway: 18, combined: 16.2 },
  co2: 31,
  annualFuelCostUsd: 1250,
  range: 966,
  electricRange: 72,
  utilityFactor: 0.71,
  fuelEconomyScore: 9,
  greenhouseGasScore: 10,
  fiveYearSavingsUsd: 7500,
}
