import { ConsumptionUnit } from '@/core/Vehicle/domain/headlineConsumption'

/** Every text the app shows on screen, in Spanish */
export const TEXTS = {
  appName: 'Comparador de coches',
  nav: {
    home: 'Inicio',
    compare: (count: number) => `Comparar (${count})`,
  },
  units: {
    litersPer100Km: 'L/100 km',
    kwhPer100Km: 'kWh/100 km',
  } satisfies Record<ConsumptionUnit, string>,
  search: {
    placeholder: 'Filtrar por modelo o carrocería',
    allFuels: 'Todos los combustibles',
    consumption: 'L/100 km',
    greater: 'Mayor que',
    equal: 'Igual a',
    less: 'Menor que',
    value: 'Valor',
  },
  home: {
    error: 'Error al cargar los coches',
    empty: 'No hay coches',
    compareBar: (count: number, max: number) => `${count} de ${max} elegidos · Comparar ahora →`,
  },
  card: {
    city: 'Ciudad',
    highway: 'Carretera',
    co2: 'CO₂ g/km',
    fuelPerYear: 'Combustible / año',
  },
  compareButton: {
    add: '+ Comparar',
    addLong: '+ Añadir a la comparación',
    added: '✓ En la comparación',
  },
  details: {
    error: 'Error al cargar el coche',
    combined: 'combinado',
    fuelEconomyScore: 'Puntuación de consumo',
    greenhouseGasScore: 'Puntuación de gases de efecto invernadero',
    specs: 'Datos técnicos',
    vehicleClass: 'Carrocería',
    drive: 'Tracción',
    transmission: 'Cambio',
    engine: 'Motor',
    fuelType: 'Combustible',
    cityConsumption: 'Consumo en ciudad',
    highwayConsumption: 'Consumo en carretera',
    combinedConsumption: 'Consumo combinado',
    co2: 'CO₂ por el escape',
    annualFuelCost: 'Gasto anual en combustible',
    range: 'Autonomía',
    electricMotor: 'Motor eléctrico',
    electricityConsumption: 'Consumo eléctrico',
    electricRange: 'Autonomía eléctrica',
    utilityFactor: 'Factor de utilidad',
    engineDescription: (cylinders: string, displacement: string) => `${cylinders} cil., ${displacement} L`,
    fiveYearSavings: (amount: string) =>
      `Ahorras ${amount} $ en combustible en 5 años frente al coche nuevo medio.`,
    fiveYearSpending: (amount: string) =>
      `Gastas ${amount} $ más en combustible en 5 años que el coche nuevo medio.`,
  },
  compare: {
    title: 'Comparar',
    error: 'Error al cargar la comparación',
    empty: 'Aún no hay nada que comparar',
    pickBefore: 'Elige hasta 3 coches del ',
    pickLink: 'listado',
    remove: 'Quitar',
    fuel: 'Combustible',
    vehicleClass: 'Carrocería',
    drive: 'Tracción',
    transmission: 'Cambio',
    cityLiters: 'Consumo ciudad (L/100 km)',
    highwayLiters: 'Consumo carretera (L/100 km)',
    combinedLiters: 'Consumo combinado (L/100 km)',
    electricity: 'Consumo eléctrico (kWh/100 km)',
    co2: 'CO₂ (g/km)',
    annualFuelCost: 'Gasto anual en combustible ($)',
    range: 'Autonomía (km)',
    fuelEconomyScore: 'Puntuación de consumo',
  },
}
